/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/campaign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Campaign */
        post: operations["create_campaign_api_campaign_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdvertiserProfile */
        AdvertiserProfile: {
            /** Inferred Category */
            inferred_category: string;
            /**
             * Inferred Subcategories
             * @default []
             */
            inferred_subcategories: string[];
            /**
             * Catalog Categories
             * @default []
             */
            catalog_categories: string[];
            /**
             * Price Tier
             * @enum {string}
             */
            price_tier: "budget" | "mid" | "premium" | "luxury";
            /**
             * Brand Tone
             * @default []
             */
            brand_tone: string[];
            /** Target Age Range */
            target_age_range?: [
                number,
                number
            ] | null;
            /** Target Gender Lean */
            target_gender_lean?: ("female" | "male") | null;
            /** Confidence */
            confidence: number;
            /**
             * Ambiguity Notes
             * @default []
             */
            ambiguity_notes: string[];
            /** Raw Input */
            raw_input: string;
        };
        /** BidStrategy */
        BidStrategy: {
            /**
             * Model
             * @enum {string}
             */
            model: "CPM" | "CPC" | "CPA";
            /** Rationale */
            rationale: string;
        };
        /** Budget */
        Budget: {
            /** Total Usd */
            total_usd: number;
            /** Daily Usd */
            daily_usd: number;
            /** Flight Days */
            flight_days: number;
        };
        /** CampaignConfig */
        CampaignConfig: {
            advertiser: components["schemas"]["AdvertiserProfile"];
            viability: components["schemas"]["Viability"];
            targeting: components["schemas"]["Targeting"];
            /** Publishers */
            publishers: components["schemas"]["PublisherRecommendation"][];
            /** Excluded Publishers */
            excluded_publishers: components["schemas"]["ExcludedPublisher"][];
            /** Personas */
            personas: components["schemas"]["PersonaMatch"][];
            /** Creatives */
            creatives: components["schemas"]["Creative"][];
            budget: components["schemas"]["Budget"];
            bid_strategy: components["schemas"]["BidStrategy"];
            meta: components["schemas"]["RunMeta"];
        };
        /** CampaignRequest */
        CampaignRequest: {
            /** Business Description */
            business_description: string;
            /**
             * Total Budget Usd
             * @default 5000
             */
            total_budget_usd: number;
            /**
             * Flight Days
             * @default 14
             */
            flight_days: number;
        };
        /** Creative */
        Creative: {
            /** Persona Id */
            persona_id: string;
            /** Headline */
            headline: string;
            /** Body */
            body: string;
        };
        /** ExcludedPublisher */
        ExcludedPublisher: {
            /** Publisher Id */
            publisher_id: string;
            /** Name */
            name: string;
            /** Score */
            score: number;
            /** Reason */
            reason: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PersonaMatch */
        PersonaMatch: {
            /** Persona Id */
            persona_id: string;
            /** Name */
            name: string;
            /** Fit Score */
            fit_score: number;
            /** Fit Label */
            fit_label: string;
            /** Reasoning */
            reasoning: string;
        };
        /** PublisherRecommendation */
        PublisherRecommendation: {
            /** Publisher Id */
            publisher_id: string;
            /** Name */
            name: string;
            /** Match Score */
            match_score: number;
            breakdown: components["schemas"]["PublisherScoreBreakdown"];
            /** Reasoning */
            reasoning: string;
            /** Budget Allocation Pct */
            budget_allocation_pct: number;
            /** Budget Allocation Usd */
            budget_allocation_usd: number;
            /**
             * Suggested Bid Model
             * @enum {string}
             */
            suggested_bid_model: "CPM" | "CPC" | "CPA";
            /** Suggested Bid Range */
            suggested_bid_range: [
                number,
                number
            ];
            /** Monthly Impressions */
            monthly_impressions: number;
            /** Estimated Impressions */
            estimated_impressions: number;
            /** Inventory Share Pct */
            inventory_share_pct: number;
        };
        /** PublisherScoreBreakdown */
        PublisherScoreBreakdown: {
            /** Category Fit */
            category_fit: number;
            /** Price Fit */
            price_fit: number;
            /** Audience Fit */
            audience_fit: number;
            /** Tone Fit */
            tone_fit: number;
        };
        /** RunMeta */
        RunMeta: {
            /** Generated At */
            generated_at: string;
            /** Pipeline Version */
            pipeline_version: string;
            /** Model */
            model: string;
        };
        /** Targeting */
        Targeting: {
            /** Age Range */
            age_range: [
                number,
                number
            ] | null;
            /** Gender Lean */
            gender_lean: string | null;
            /** Income Tiers */
            income_tiers: string[];
            /** Geos */
            geos: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * Viability
         * @description Whether this catalog can serve this advertiser at all - a separate
         *     question from whether we understood them (that's AdvertiserProfile.
         *     confidence). "B2B SaaS for dental practices" is a perfectly understood
         *     input with no viable inventory here.
         */
        Viability: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "weak" | "no_match";
            /** Headline */
            headline: string;
            /** Detail */
            detail: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_campaign_api_campaign_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CampaignRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignConfig"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
